---
ansible_host: your-server

# credentials declaration, this are the native ansible variables
ansible_user: "{{ vault_user }}" # vault_user should reside in ./vault.yml => defined by it
ansible_password: "{{ vault_password }}" # vault_password should reside in ./vault.yml
ansible_become_password: "{{ vault_become_pw }}" # vault_user or vault_become_password should reside in ./vault.yml

# the variable names are expected to be defined
# vault_user: ""
# vault_password: ""
# vault_become_pw: ""

# workaround for ubuntu 26.04: ansible cannot work with the newest sudo.rs
# as long as its not fixed: use the old sudo.ws
ansible_become_exe: /usr/bin/sudo.ws
